[project]
name = "report-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "streamlit>=1.46.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ruff>=0.12.2",
]
