services:
  report-reader:
    image: ghcr.io/qin2dim/report-reader:latest
    restart: always
    container_name: report-reader
    ports:
      - "31313:8501"
    volumes:
      - "./logs:/app/app/logs"
    command: uv run streamlit run app/main.py
